language: node_js
node_js:
  - node
  - lts/*
  - 15
  - 14
  - 13
  - 12
  - 11
  - 10

cache: yarn

script:
  - ./bin/run --version
  - ./bin/run --help
  - yarn run test

deploy:
  provider: script
  script: yarn run deploy
  on:
    branch: master

after_success:
  - ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
