"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.mapKeysDeep = exports.isString = exports.isNative = exports.noop = void 0;
const lodash_1 = require("lodash");
const noop = () => { };
exports.noop = noop;
const isNative = (obj) => ["number", "string", "bigint", "boolean"].includes(typeof obj);
exports.isNative = isNative;
const isString = (obj) => typeof obj === "string";
exports.isString = isString;
const mapKeysDeep = (obj, replacer) => lodash_1.mapValues(lodash_1.mapKeys(obj, replacer), (val) => lodash_1.isObject(val) ? exports.mapKeysDeep(val, replacer) : val);
exports.mapKeysDeep = mapKeysDeep;
