name: CI/Publish GH Page
on:
  push:
    branches:
      - ignroe
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn
        working-directory: ./playground
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - name: Build
        run: yarn build
        working-directory: ./playground
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: playground/build
