name: CI/Update playground package
on:
  push:
    branches:
      - master
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn run test:ci
      - uses: actions/checkout@v2
        with:
          ref: playground-version
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Commit & Push
        run: |
          git config --global user.name 'Playground bot 🤖'
          git config --global user.email 'playground@doriaviram.com'
          git merge origin/master --allow-unrelated-histories --strategy-option theirs
          git add .
          git commit -am "Update playground version 🤖" --no-verify
          git push
